### ISSUE TITLE
read_csv fails depending on data

### ISSUE THREAD

**Issue by romanovacca** [ritchie46/polars#470]
I get the following error when reading in my csv.

`thread '<unnamed>' panicked at 'arrow array: CDataInterface("The datatype \"tss:\" is not supported in the Rust implementation")', py-polars/src/arrow_interop/to_rust.rs:21:71
`

I have a snippet of the data here:
<img width="469" alt="Screenshot 2021-03-22 at 23 40 47" src="https://user-images.githubusercontent.com/12878583/112067284-1596dc00-8b68-11eb-9bdf-4550bf329ee4.png">

The error has something to do with the timestamp data. Obvious there are no quotes around the timestamp, I tried setting the sep parameter, but that already defaults to ','. 

If I place single quotes around the timestamp, reading succeeds. Reading this in pandas without quotes does work.

Currently using py-polars==0.6.7

**Comment by ritchie46** [comment]
Romana! Nice to see you here!😁

It could be that we already fixed this one. Py-polars was renamed to polars. Could you install the latest version with `pip install polars` and try again?

**Comment by romanovacca** [comment]
Oh wow, rookie mistake from my end haha.
However, I still get the same error, while using polars==0.7.1

To me it looks a bit like the same problem as in this PR [#381](https://github.com/ritchie46/polars/issues/381#issuecomment-791211333_)

**Comment by ritchie46** [comment]
Yes, Rust arrow hasn't yet implemented all datatypes in the C FFI. We can circumvent that for now. If you set the [use_pyarrow](https://github.com/ritchie46/polars/blob/f2553f820e84553bb63f90c36b3493945732f60a/py-polars/polars/functions.py#L63) argument to `False`, you parse the csv with Polars' csv-parser instead of pyarrows. 

The date types are then just read as  utf8 values. You can then parse them into `date64` types similar to what is done in #381.
